export const criminalLawWords = [
  { word: "misdemeanor", hint: "A less serious crime usually punishable by fines or short jail time" },
  { word: "felony", hint: "A serious crime typically punishable by imprisonment" },
  { word: "arrest", hint: "The act of taking someone into custody by legal authority" },
  { word: "parole", hint: "Conditional release from prison before a sentence is completed" },
  { word: "probation", hint: "Supervised release instead of serving time in jail or prison" },
  { word: "verdict", hint: "The final decision made by a jury in a case" },
  { word: "wiretap", hint: "The monitoring of private communications, often by law enforcement" },
  { word: "corroboration", hint: "Independent evidence that supports other testimony" },
  { word: "testimony", hint: "Statements made under oath in court" },
  { word: "prosecutor", hint: "A lawyer who represents the government in a criminal case" },
  { word: "homicide", hint: "The killing of one person by another" },
  { word: "manslaughter", hint: "The unlawful killing of a person without premeditation" },
  { word: "informant", hint: "A person who provides information to authorities" },
  { word: "burglary", hint: "Entering a building unlawfully with intent to commit a crime" },
  { word: "robbery", hint: "Taking property from someone using force or threats" },
  { word: "bribery", hint: "Offering something of value to unlawfully influence an action" },
  { word: "perjury", hint: "Lying under oath in a legal proceeding" },
  { word: "extortion", hint: "Obtaining something through threats or coercion" },
  { word: "trafficking", hint: "Illegal trade or movement of goods or people" },
  { word: "bail", hint: "Money paid to secure temporary release from custody" },
  { word: "jail", hint: "A facility for short-term detention or for serving sentences on minor offenses" },
  { word: "prison", hint: "A facility for serving long-term sentences for serious offenses" },
  { word: "obstruction", hint: "Interfering with the administration of justice" },
  { word: "insanity", hint: "A mental condition affecting legal responsibility" },
  { word: "justification", hint: "A lawful reason for an otherwise criminal act" },
  { word: "quash", hint: "To void or invalidate a legal action" },
  { word: "recidivism", hint: "Repeated criminal behavior after punishment" },
  { word: "immunity", hint: "Protection from prosecution in exchange for testimony" },
  { word: "acquittal", hint: "A legal judgment that a person is not guilty" },
  { word: "indictment", hint: "A formal charge issued by a grand jury" },
  { word: "arraignment", hint: "A court proceeding where charges are formally read" },
  { word: "custody", hint: "Being held by law enforcement or authorities" },
  { word: "solicitation", hint: "Encouraging or requesting someone to commit a crime" },
  { word: "interrogation", hint: "Questioning of a suspect by police" },
  { word: "confession", hint: "A statement admitting guilt" },
  { word: "alibi", hint: "A claim or evidence that someone was elsewhere during a crime" },
  { word: "warrant", hint: "A legal document authorizing police action" },
  { word: "search", hint: "Looking for evidence related to a crime" },
  { word: "seizure", hint: "Taking property as evidence by legal authority" },
  { word: "deterrence", hint: "Prevention of crime through fear of punishment" },
  { word: "rehabilitation", hint: "Reforming an offender to prevent future crimes" },
  { word: "restitution", hint: "Repayment made to a victim for loss or harm" },
  { word: "accomplice", hint: "Someone who participates in a crime with another" },
  { word: "incarceration", hint: "Confinement in a jail or prison" },
  { word: "contraband", hint: "Illegal goods that are prohibited by law" },
  { word: "plea", hint: "A defendant’s formal response to charges" },
  { word: "conspiracy", hint: "An agreement between two or more people to commit a crime" }, 
  { word: "forgery", hint: "Creating or altering a document with intent to deceive" },
  { word: "arson", hint: "Deliberately setting fire to property" },
  { word: "kidnapping", hint: "Unlawfully taking and holding a person against their will" }
];

export const civilLawWords = [
  { word: "contract", hint: "A legally binding agreement between two or more parties" },
  { word: "tort", hint: "A wrongful act that causes harm and leads to legal liability" },
  { word: "negligence", hint: "Failure to take proper care resulting in damage or injury" },
  { word: "liability", hint: "Legal responsibility for one’s actions or omissions" },
  { word: "damages", hint: "Money awarded to compensate for harm or loss" },
  { word: "plaintiff", hint: "The person who brings a lawsuit in court" },
  { word: "defendant", hint: "The person being sued in a civil case" },
  { word: "breach", hint: "The violation of a legal obligation or agreement" },
  { word: "easement", hint: "The right to use another person's land for a specific purpose" },
  { word: "settlement", hint: "An agreement reached to resolve a dispute without trial" },
  { word: "foreclosure", hint: "The legal process of taking property due to unpaid debt" },
  { word: "arbitration", hint: "A process where a neutral third party resolves a dispute outside court" },
  { word: "mediation", hint: "A negotiation process assisted by a neutral third party" },
  { word: "injunction", hint: "A court order requiring someone to act or stop acting" },
  { word: "nullification", hint: "The legal invalidation of a contract or agreement" },
  { word: "liquidated", hint: "A fixed amount of damages agreed upon in a contract" },
  { word: "judgment", hint: "The final decision made by a court" },
  { word: "assignment", hint: "The transfer of rights or property from one party to another" },
  { word: "discovery", hint: "The pre-trial process of exchanging evidence between parties" },
  { word: "deposition", hint: "Sworn out-of-court testimony recorded for later use in trial" },
  { word: "rescission", hint: "The cancellation of a contract by mutual agreement or legal grounds" },
  { word: "lease", hint: "A contract granting use of property for a specified time" },
  { word: "tenant", hint: "A person who rents property from another" },
  { word: "landlord", hint: "A person who owns property and rents it out" },
  { word: "consideration", hint: "Something of value exchanged between parties in a contract" },
  { word: "title", hint: "Legal proof of ownership of property" },
  { word: "equity", hint: "Fairness in legal matters or ownership value in property" },
  { word: "trust", hint: "A legal arrangement where one party holds property for another" },
  { word: "probate", hint: "The legal process of handling a deceased person’s estate" },
  { word: "inheritance", hint: "Property or assets received from someone who has died" },
  { word: "will", hint: "A legal document stating how assets are distributed after death" },
  { word: "estate", hint: "All the money and property owned by a person" },
  { word: "custody", hint: "Legal responsibility for the care of a child" },
  { word: "alimony", hint: "Financial support paid to a former spouse after divorce" },
  { word: "estoppel", hint: "Preventing someone from contradicting a previous claim or action" },
  { word: "joinder", hint: "The inclusion of additional parties or claims in a lawsuit" },
  { word: "guardian", hint: "A person legally responsible for another individual" },
  { word: "fiduciary", hint: "A person required to act in another’s best interest" },
  { word: "pleading", hint: "Formal written statements of claims or defenses in a case" },
  { word: "duty", hint: "A responsibility required by law or agreement" },
  { word: "escrow", hint: "Money or property held by a third party until conditions are met" },
  { word: "partition", hint: "The division of property among co-owners" },
  { word: "nuisance", hint: "An action that interferes with the use of property" },
  { word: "appraisal", hint: "An official assessment of the value of property" },
  { word: "defamation", hint: "False statements that harm someone’s reputation" },
  { word: "libel", hint: "Written false statements that damage reputation" },
  { word: "slander", hint: "Spoken false statements that damage reputation" },
  { word: "grantor", hint: "A person who transfers property or rights to another" },
  { word: "grantee", hint: "A person who receives property or rights from another" },
  { word: "clause", hint: "A specific provision within a contract" }
];

export const caseCheckpoints = [{checkpoint: "Jury selection", background: "bg-orange-50", border: "border-orange-500"},
                                {checkpoint: "Opening statements", background: "bg-blue-50", border: "border-blue-500"},
                                {checkpoint: "Your case-in-chief", background: "bg-red-50", border: "border-red-500"},
                                {checkpoint: "Opponent's case-in-chief", background: "bg-green-50", border: "border-green-500"},
                                {checkpoint: "Your rebuttal case", background: "bg-cyan-50", border: "border-cyan-500"},
                                {checkpoint: "Closing arguments", background: "bg-yellow-50", border: "border-yellow-500"},
                                {checkpoint: "Jury deliberations", background: "bg-purple-50", border: "border-purple-500"}]