export const criminalLawWords = [
  { word: "actus reus", hint: "The physical act required to commit a crime" },
  { word: "mens rea", hint: "The mental intent behind committing a crime" },
  { word: "nolle prosequi", hint: "A prosecutor’s decision to formally drop charges" },
  { word: "allocution", hint: "A defendant’s statement to the court before sentencing" },
  { word: "bill of particulars", hint: "A document clarifying details of criminal charges" },
  { word: "brady material", hint: "Evidence favorable to the defendant that prosecutors must disclose" },
  { word: "capias", hint: "A court order directing law enforcement to arrest someone" },
  { word: "corroboration", hint: "Independent evidence that supports other testimony" },
  { word: "crimen falsi", hint: "Crimes involving dishonesty, such as fraud or perjury" },
  { word: "de novo review", hint: "A fresh review of a case without relying on prior rulings" },
  { word: "dismissal with prejudice", hint: "Charges dismissed permanently and cannot be refiled" },
  { word: "dismissal without prejudice", hint: "Charges dismissed but may be filed again later" },
  { word: "exculpatory evidence", hint: "Evidence that tends to show a defendant’s innocence" },
  { word: "felony murder rule", hint: "Rule making a death during a felony chargeable as murder" },
  { word: "grand jury", hint: "A jury that decides whether criminal charges should be filed" },
  { word: "habitual offender", hint: "A person repeatedly convicted of crimes" },
  { word: "hot pursuit", hint: "Immediate police chase allowing warrantless action" },
  { word: "information", hint: "A formal criminal charge issued without a grand jury" },
  { word: "joinder", hint: "Combining multiple charges or defendants into one trial" },
  { word: "miranda waiver", hint: "A suspect’s voluntary surrender of Miranda rights" },
  { word: "nolo contendere", hint: "A plea accepting punishment without admitting guilt" },
  { word: "obstruction of justice", hint: "Interfering with legal proceedings or investigations" },
  { word: "particularity requirement", hint: "Warrants must clearly specify places and items" },
  { word: "peremptory challenge", hint: "Jury removal without stating a reason" },
  { word: "probation violation", hint: "Failure to comply with probation conditions" },
  { word: "proffer", hint: "An offer of information in exchange for leniency" },
  { word: "quash", hint: "To void or invalidate a legal action" },
  { word: "recidivism", hint: "Repeated criminal behavior after punishment" },
  { word: "restitution", hint: "Court-ordered repayment to crime victims" },
  { word: "severance", hint: "Splitting defendants or charges into separate trials" },
  { word: "suasponte", hint: "Action taken by a judge without a request" },
  { word: "suppress evidence", hint: "To exclude illegally obtained evidence" },
  { word: "terry stop", hint: "Brief police stop based on reasonable suspicion" },
  { word: "transferred intent", hint: "Intent applied to an unintended victim" },
  { word: "venue", hint: "The geographic location where a trial occurs" },
  { word: "voir dire", hint: "The process of questioning potential jurors" },
  { word: "waiver of counsel", hint: "Choosing to represent oneself in court" },
  { word: "weapon enhancement", hint: "Sentence increase for using a weapon" },
  { word: "willful blindness", hint: "Deliberate ignorance of illegal activity" },
  { word: "wobbler", hint: "A crime chargeable as either a felony or misdemeanor" },
  { word: "chain of custody", hint: "Documentation tracking how evidence is handled" },
  { word: "competency hearing", hint: "Evaluation of a defendant’s mental fitness" },
  { word: "constructive possession", hint: "Control over illegal items without physical possession" },
  { word: "cruel and unusual punishment", hint: "Punishment prohibited by the Constitution" },
  { word: "entrapment defense", hint: "Claim that police induced criminal conduct" },
  { word: "indeterminate sentence", hint: "Sentence without a fixed release date" },
  { word: "misjoinder", hint: "Improper combination of charges or defendants" },
  { word: "penal statute", hint: "A law defining criminal punishment" },
  { word: "pretext stop", hint: "Traffic stop used to investigate another crime" },
  { word: "victim impact statement", hint: "Statement describing harm suffered by a victim" }
];

export const civilLawWords = [
  { word: "abatement", hint: "Temporary suspension of legal proceedings" },
  { word: "adhesion contract", hint: "Standard contract offered on a take-it-or-leave-it basis" },
  { word: "affirmative defense", hint: "Defense asserting facts that avoid liability" },
  { word: "amicus curiae", hint: "Non-party who offers information to the court" },
  { word: "assumpsit", hint: "Old legal action for enforcing contracts" },
  { word: "bona fide purchaser", hint: "Buyer who purchases property without notice of defects" },
  { word: "caveat emptor", hint: "Principle meaning “buyer beware”" },
  { word: "certiorari", hint: "Higher court review of a lower court decision" },
  { word: "collateral estoppel", hint: "Prevents re-litigation of previously decided issues" },
  { word: "compensatory damages", hint: "Money awarded to cover actual losses" },
  { word: "contributory negligence", hint: "Plaintiff fault that may bar recovery" },
  { word: "declaratory judgment", hint: "Court ruling that defines legal rights" },
  { word: "detrimental reliance", hint: "Harm caused by relying on a promise" },
  { word: "easement", hint: "Legal right to use another person’s land" },
  { word: "equitable estoppel", hint: "Prevents denying facts due to prior conduct" },
  { word: "escrow", hint: "Funds held by a neutral third party" },
  { word: "forum shopping", hint: "Choosing a court thought to be more favorable" },
  { word: "indemnification", hint: "Compensation for loss or damage" },
  { word: "interpleader", hint: "Lawsuit to determine rightful claimant" },
  { word: "laches", hint: "Loss of rights due to unreasonable delay" },
  { word: "liquidated damages", hint: "Pre-agreed damages in a contract" },
  { word: "lispendens", dhint: "Notice of pending litigation involving property" },
  { word: "mitigation of damages", hint: "Duty to minimize losses after harm" },
  { word: "novation", hint: "Replacement of a contract party" },
  { word: "parol evidence rule", hint: "Limits outside evidence contradicting a contract" },
  { word: "piercing the corporate veil", hint: "Holding owners personally liable for company acts" },
  { word: "quantum meruit", hint: "Payment for services without a formal contract" },
  { word: "quiet title", hint: "Action resolving property ownership disputes" },
  { word: "rescission", hint: "Cancellation of a contract" },
  { word: "specific performance", hint: "Court order requiring contract fulfillment" },
  { word: "stipulation", hint: "Agreement between parties on certain facts" },
  { word: "subrogation", hint: "Insurer assuming another’s legal rights" },
  { word: "tortfeasor", hint: "Person who commits a civil wrong" },
  { word: "unjust enrichment", hint: "Unfair benefit gained at another’s expense" },
  { word: "usury", hint: "Charging illegally high interest" },
  { word: "vicarious liability", hint: "Liability for another person’s actions" },
  { word: "venue transfer", hint: "Moving a case to a different court" },
  { word: "writ of mandamus", hint: "Order compelling an official act" },
  { word: "wrongful termination", hint: "Illegal dismissal from employment" },
  { word: "zoning ordinance", hint: "Law regulating land use" },
  { word: "accord and satisfaction", hint: "Agreement resolving a disputed claim" },
  { word: "comparative negligence", hint: "Fault divided among parties" },
  { word: "constructive trust", hint: "Court-imposed trust to prevent injustice" },
  { word: "equitative relief", hint: "Non-monetary court remedy" },
  { word: "fiduciary duty", hint: "Duty of loyalty and care" },
  { word: "injunction bond", hint: "Security required before issuing an injunction" },
  { word: "joinder of claims", hint: "Combining multiple claims into one lawsuit" },
  { word: "legal malpractice", hint: "Attorney negligence harming a client" },
  { word: "preponderance of evidence", hint: "More likely than not standard of proof" },
  { word: "replevin", hint: "Lawsuit to recover wrongfully taken property" }
];

export const caseCheckpoints = [{checkpoint: "Jury selection", background: "bg-orange-50", border: "border-orange-500"},
                                {checkpoint: "Opening statements", background: "bg-blue-50", border: "border-blue-500"},
                                {checkpoint: "Your case-in-chief", background: "bg-red-50", border: "border-red-500"},
                                {checkpoint: "Opponent's case-in-chief", background: "bg-green-50", border: "border-green-500"},
                                {checkpoint: "Your rebuttal case", background: "bg-cyan-50", border: "border-cyan-500"},
                                {checkpoint: "Closing arguments", background: "bg-yellow-50", border: "border-yellow-500"},
                                {checkpoint: "Jury deliberations", background: "bg-purple-50", border: "border-purple-500"}]