export const criminalLawWords = [
  { word: "actus reus", definition: "The physical act required to commit a crime." },
  { word: "mens rea", definition: "The mental intent behind committing a crime." },
  { word: "nolle prosequi", definition: "A prosecutor’s decision to formally drop charges." },
  { word: "allocution", definition: "A defendant’s statement to the court before sentencing." },
  { word: "bill of particulars", definition: "A document clarifying details of criminal charges." },
  { word: "brady material", definition: "Evidence favorable to the defendant that prosecutors must disclose." },
  { word: "capias", definition: "A court order directing law enforcement to arrest someone." },
  { word: "corroboration", definition: "Independent evidence that supports other testimony." },
  { word: "crimen falsi", definition: "Crimes involving dishonesty, such as fraud or perjury." },
  { word: "de novo review", definition: "A fresh review of a case without relying on prior rulings." },
  { word: "dismissal with prejudice", definition: "Charges dismissed permanently and cannot be refiled." },
  { word: "dismissal without prejudice", definition: "Charges dismissed but may be filed again later." },
  { word: "exculpatory evidence", definition: "Evidence that tends to show a defendant’s innocence." },
  { word: "felony murder rule", definition: "Rule making a death during a felony chargeable as murder." },
  { word: "grand jury", definition: "A jury that decides whether criminal charges should be filed." },
  { word: "habitual offender", definition: "A person repeatedly convicted of crimes." },
  { word: "hot pursuit", definition: "Immediate police chase allowing warrantless action." },
  { word: "information", definition: "A formal criminal charge issued without a grand jury." },
  { word: "joinder", definition: "Combining multiple charges or defendants into one trial." },
  { word: "miranda waiver", definition: "A suspect’s voluntary surrender of Miranda rights." },
  { word: "nolo contendere", definition: "A plea accepting punishment without admitting guilt." },
  { word: "obstruction of justice", definition: "Interfering with legal proceedings or investigations." },
  { word: "particularity requirement", definition: "Warrants must clearly specify places and items." },
  { word: "peremptory challenge", definition: "Jury removal without stating a reason." },
  { word: "probation violation", definition: "Failure to comply with probation conditions." },
  { word: "proffer", definition: "An offer of information in exchange for leniency." },
  { word: "quash", definition: "To void or invalidate a legal action." },
  { word: "recidivism", definition: "Repeated criminal behavior after punishment." },
  { word: "restitution", definition: "Court-ordered repayment to crime victims." },
  { word: "severance", definition: "Splitting defendants or charges into separate trials." },
  { word: "suasponte", definition: "Action taken by a judge without a request." },
  { word: "suppress evidence", definition: "To exclude illegally obtained evidence." },
  { word: "terry stop", definition: "Brief police stop based on reasonable suspicion." },
  { word: "transferred intent", definition: "Intent applied to an unintended victim." },
  { word: "venue", definition: "The geographic location where a trial occurs." },
  { word: "voir dire", definition: "The process of questioning potential jurors." },
  { word: "waiver of counsel", definition: "Choosing to represent oneself in court." },
  { word: "weapon enhancement", definition: "Sentence increase for using a weapon." },
  { word: "willful blindness", definition: "Deliberate ignorance of illegal activity." },
  { word: "wobbler", definition: "A crime chargeable as either a felony or misdemeanor." },
  { word: "chainofcustody", definition: "Documentation tracking how evidence is handled." },
  { word: "competency hearing", definition: "Evaluation of a defendant’s mental fitness." },
  { word: "constructive possession", definition: "Control over illegal items without physical possession." },
  { word: "cruel and unusual punishment", definition: "Punishment prohibited by the Constitution." },
  { word: "entrapment defense", definition: "Claim that police induced criminal conduct." },
  { word: "indeterminate sentence", definition: "Sentence without a fixed release date." },
  { word: "misjoinder", definition: "Improper combination of charges or defendants." },
  { word: "penal statute", definition: "A law defining criminal punishment." },
  { word: "pretext stop", definition: "Traffic stop used to investigate another crime." },
  { word: "victim impact statement", definition: "Statement describing harm suffered by a victim." }
];

export const civilLawWords = [
  { word: "abatement", definition: "Temporary suspension of legal proceedings." },
  { word: "adhesion contract", definition: "Standard contract offered on a take-it-or-leave-it basis." },
  { word: "affirmative defense", definition: "Defense asserting facts that avoid liability." },
  { word: "amicus curiae", definition: "Non-party who offers information to the court." },
  { word: "assumpsit", definition: "Old legal action for enforcing contracts." },
  { word: "bona fide purchaser", definition: "Buyer who purchases property without notice of defects." },
  { word: "caveat emptor", definition: "Principle meaning “buyer beware.”" },
  { word: "certiorari", definition: "Higher court review of a lower court decision." },
  { word: "collateral estoppel", definition: "Prevents re-litigation of previously decided issues." },
  { word: "compensatory damages", definition: "Money awarded to cover actual losses." },
  { word: "contributory negligence", definition: "Plaintiff fault that may bar recovery." },
  { word: "declaratory judgment", definition: "Court ruling that defines legal rights." },
  { word: "detrimental reliance", definition: "Harm caused by relying on a promise." },
  { word: "easement", definition: "Legal right to use another person’s land." },
  { word: "equitable estoppel", definition: "Prevents denying facts due to prior conduct." },
  { word: "escrow", definition: "Funds held by a neutral third party." },
  { word: "forum shopping", definition: "Choosing a court thought to be more favorable." },
  { word: "indemnification", definition: "Compensation for loss or damage." },
  { word: "interpleader", definition: "Lawsuit to determine rightful claimant." },
  { word: "laches", definition: "Loss of rights due to unreasonable delay." },
  { word: "liquidated damages", definition: "Pre-agreed damages in a contract." },
  { word: "lispendens", definition: "Notice of pending litigation involving property." },
  { word: "mitigation of damages", definition: "Duty to minimize losses after harm." },
  { word: "novation", definition: "Replacement of a contract party." },
  { word: "parol evidence rule", definition: "Limits outside evidence contradicting a contract." },
  { word: "piercing the corporate veil", definition: "Holding owners personally liable for company acts." },
  { word: "quantummeruit", definition: "Payment for services without a formal contract." },
  { word: "quiettitle", definition: "Action resolving property ownership disputes." },
  { word: "rescission", definition: "Cancellation of a contract." },
  { word: "specific performance", definition: "Court order requiring contract fulfillment." },
  { word: "stipulation", definition: "Agreement between parties on certain facts." },
  { word: "subrogation", definition: "Insurer assuming another’s legal rights." },
  { word: "tortfeasor", definition: "Person who commits a civil wrong." },
  { word: "unjust enrichment", definition: "Unfair benefit gained at another’s expense." },
  { word: "usury", definition: "Charging illegally high interest." },
  { word: "vicarious liability", definition: "Liability for another person’s actions." },
  { word: "venue transfer", definition: "Moving a case to a different court." },
  { word: "writ of mandamus", definition: "Order compelling an official act." },
  { word: "wrongful termination", definition: "Illegal dismissal from employment." },
  { word: "zoning ordinance", definition: "Law regulating land use." },
  { word: "accord and satisfaction", definition: "Agreement resolving a disputed claim." },
  { word: "comparative negligence", definition: "Fault divided among parties." },
  { word: "constructive trust", definition: "Court-imposed trust to prevent injustice." },
  { word: "equitative relief", definition: "Non-monetary court remedy." },
  { word: "fiduciary duty", definition: "Duty of loyalty and care." },
  { word: "injunction bond", definition: "Security required before issuing an injunction." },
  { word: "joinder of claims", definition: "Combining multiple claims into one lawsuit." },
  { word: "legal malpractice", definition: "Attorney negligence harming a client." },
  { word: "preponderance of evidence", definition: "More likely than not standard of proof." },
  { word: "replevin", definition: "Lawsuit to recover wrongfully taken property." }
];

export const caseCheckpoints = ["Jury selection", "Opening statements", "Your case-in-chief", "Opponent's case-in-chief", "Your rebuttal case", "Closing arguments"]